: START-FRESH             ( state start -- state result )     EXACT-START? FRESH-ID? ADD-START ATTEMPT-STARTED ;
: START-REPLAY            ( state start -- state result )     EXACT-START? EXACT-START-REPLAY? KEEP-STATE IDEMPOTENT-REPLAY ;
: REJECT-START-CONFLICT   ( state start -- state result )     EXACT-START? START-CONFLICT? KEEP-STATE ATTEMPT-IDENTITY-CONFLICT ;
: END-RESULT              ( state terminal -- state result )  EXACT-TERMINAL? EXACT-RUNNING? FRESH-TERMINAL? KIND-RESULT? ADD-TERMINAL ATTEMPT-ENDED-WITH-RESULT ;
: END-NO-RESULT           ( state terminal -- state result )  EXACT-TERMINAL? EXACT-RUNNING? FRESH-TERMINAL? KIND-NO-RESULT? ADD-TERMINAL ATTEMPT-ENDED-WITH-NO-RESULT ;
: END-REPLAY              ( state terminal -- state result )  EXACT-TERMINAL? EXACT-TERMINAL-REPLAY? KEEP-STATE IDEMPOTENT-REPLAY ;
: REJECT-END-CONFLICT     ( state terminal -- state result )  EXACT-TERMINAL? TERMINAL-CONFLICT? KEEP-STATE TERMINAL-ATTEMPT-IMMUTABLE ;
: REJECT-END-NOT-RUNNING  ( state terminal -- state result )  EXACT-TERMINAL? NO-TERMINAL-FOR-ID? NOT-EXACT-RUNNING? KEEP-STATE ATTEMPT-NOT-RUNNING ;
