from __future__ import annotations

import json
import shutil
from pathlib import Path

from tools.alpha4_runtime_seed_extension import (
    check_seed_companion_bases,
    parse_seed_binding,
    sha256,
)

ROOT = Path(__file__).resolve().parents[1]
MANIFEST = ROOT / "runtime/alpha4/RUNTIME.aset"


class ReleaseProfileError(RuntimeError):
    pass


def require(condition: bool, message: str) -> None:
    if not condition:
        raise ReleaseProfileError(message)


def _lines(path: Path) -> list[str]:
    return [line.strip() for line in path.read_text(encoding="utf-8").splitlines() if line.strip()]


def manifest_records(root: Path = ROOT) -> list[dict[str, str]]:
    lines = _lines(root / "runtime/alpha4/RUNTIME.aset")
    causal: dict[str, str] = {}
    for line in lines:
        if line.startswith("CAUSAL-BIND "):
            _, component_id, causal_transition = line.split()
            causal[component_id] = causal_transition
    operational_map = {
        "ASET-RUNTIME-COMPONENT-START-FRESH": "START-FRESH",
        "ASET-RUNTIME-COMPONENT-START-REPLAY": "START-REPLAY",
        "ASET-RUNTIME-COMPONENT-REJECT-START-CONFLICT": "REJECT-START-CONFLICT",
        "ASET-RUNTIME-COMPONENT-END-RESULT": "END-RESULT",
        "ASET-RUNTIME-COMPONENT-END-NO-RESULT": "END-NO-RESULT",
        "ASET-RUNTIME-COMPONENT-END-REPLAY": "END-REPLAY",
        "ASET-RUNTIME-COMPONENT-REJECT-END-CONFLICT": "REJECT-END-CONFLICT",
        "ASET-RUNTIME-COMPONENT-REJECT-END-NOT-RUNNING": "REJECT-END-NOT-RUNNING",
    }
    records: list[dict[str, str]] = []
    for line in lines:
        if not line.startswith("PAIR "):
            continue
        parts = line.split()
        require(len(parts) == 6, f"bad PAIR declaration: {line}")
        _, component_id, transition_binding, relational, _reflection, pairing = parts
        require(component_id in causal, f"causal binding missing for {component_id}")
        records.append(
            {
                "component_id": component_id,
                "transition_binding": transition_binding,
                "operational": operational_map[component_id],
                "relational": relational,
                "causal": causal[component_id],
                "pairing": pairing,
                "seed_extension": "PRESERVE-SEED-STATE",
            }
        )
    require(len(records) == 8, "Runtime release companion requires eight component records")
    return records


def write_english(target: Path, seed_english_sha256: str, records: list[dict[str, str]]) -> None:
    lines = [
        "# ASET Runtime 0.1.0-alpha.4 — generated release companion extension",
        "",
        "Generated by release CI. Semantic precedence: none.",
        f"Exact Seed English base SHA-256: `{seed_english_sha256}`",
        "",
        "This document adds only Runtime-owned lifecycle expression content; "
        "the Seed companion remains the exact base expression.",
        "Every Runtime-only transition preserves the Seed state.",
        "",
    ]
    for item in records:
        lines += [
            f"### {item['component_id']}",
            f"Transition: `{item['transition_binding']}`",
            f"Operational: `{item['operational']}`",
            f"Relational: `{item['relational']}`",
            f"Causal: `{item['causal']}`",
            f"Pairing: `{item['pairing']}`",
            f"Seed extension: `{item['seed_extension']}`",
            "",
        ]
    target.write_text("\n".join(lines), encoding="utf-8")


def parse_english(path: Path) -> list[dict[str, str]]:
    text = path.read_text(encoding="utf-8")
    records: list[dict[str, str]] = []
    for section in text.split("\n### ")[1:]:
        lines = [line.strip() for line in section.splitlines() if line.strip()]
        component_id = lines[0]
        fields: dict[str, str] = {}
        for line in lines[1:]:
            if ": `" in line and line.endswith("`"):
                key, value = line.split(": `", 1)
                fields[key] = value[:-1]
        records.append(
            {
                "component_id": component_id,
                "transition_binding": fields["Transition"],
                "operational": fields["Operational"],
                "relational": fields["Relational"],
                "causal": fields["Causal"],
                "pairing": fields["Pairing"],
                "seed_extension": fields["Seed extension"],
            }
        )
    return records


def write_python(target: Path, seed_python_sha256: str, records: list[dict[str, str]]) -> None:
    metadata = json.dumps(records, indent=2, sort_keys=True)
    text = f'''"""Generated ASET Runtime 0.1.0-alpha.4 Python companion extension.

The exact ASET Seed Python companion is the base expression. Semantic precedence: none.
"""

from __future__ import annotations

import hashlib
from copy import deepcopy
from pathlib import Path
BASE_SEED_EXPRESSION_SHA256 = {seed_python_sha256!r}
BASE_SEED_EXPRESSION_PATH = (
    Path(__file__).resolve().parents[1]
    / "base"
    / "seed"
    / "python"
    / "aset_seed_alpha4.py"
)
COMPONENT_BINDINGS = {metadata}
START_FIELDS = {{"attempt_id", "attempt_digest", "runtime_binding", "descriptor_binding"}}
TERMINAL_FIELDS = {{
    "attempt_id",
    "attempt_digest",
    "terminal_kind",
    "terminal_digest",
    "terminal_binding",
    "evidence_bindings",
}}
TERMINAL_KINDS = {{"RESULT", "NO_RESULT"}}


def _sha256(path: Path) -> str:
    return "sha256:" + hashlib.sha256(path.read_bytes()).hexdigest()


def _load_seed_base() -> dict[str, Any]:
    if _sha256(BASE_SEED_EXPRESSION_PATH) != BASE_SEED_EXPRESSION_SHA256:
        raise RuntimeError("exact Seed Python companion byte identity mismatch")
    namespace: dict[str, Any] = {{}}
    source = BASE_SEED_EXPRESSION_PATH.read_text(encoding="utf-8")
    exec(compile(source, str(BASE_SEED_EXPRESSION_PATH), "exec"), namespace)
    if not callable(namespace.get("state")) or not callable(namespace.get("apply_component")):
        raise RuntimeError("exact Seed Python companion entry points missing")
    return namespace


_seed = _load_seed_base()


def state(
    starts: list[dict[str, Any]] | None = None,
    terminals: list[dict[str, Any]] | None = None,
) -> dict[str, list[dict[str, Any]]]:
    return {{
        "starts": deepcopy(starts or []),
        "terminals": deepcopy(terminals or []),
    }}


def _exact_start(value: dict[str, Any]) -> bool:
    return set(value) == START_FIELDS and all(
        isinstance(value[field], str) and value[field] for field in START_FIELDS
    )


def _exact_terminal(value: dict[str, Any]) -> bool:
    if set(value) != TERMINAL_FIELDS or value["terminal_kind"] not in TERMINAL_KINDS:
        return False
    for field in TERMINAL_FIELDS - {{"terminal_kind", "evidence_bindings"}}:
        if not isinstance(value[field], str) or not value[field]:
            return False
    evidence = value["evidence_bindings"]
    return isinstance(evidence, list) and all(isinstance(item, str) and item for item in evidence)


def _runtime_result(accepted: bool, code: str, changed: bool) -> dict[str, Any]:
    return {{
        "accepted": accepted,
        "code": code,
        "state_changed": changed,
        "seed_projection": {{"action": "STUTTER", "effect_permitted": False}},
    }}


def start_attempt(
    current: dict[str, list[dict[str, Any]]],
    start: dict[str, Any],
    seed_state: dict[str, Any],
) -> tuple[dict[str, list[dict[str, Any]]], dict[str, Any], dict[str, Any]]:
    if not _exact_start(start):
        raise ValueError("exact start record required")
    next_runtime = state(current["starts"], current["terminals"])
    next_seed = deepcopy(seed_state)
    same_id = [item for item in next_runtime["starts"] if item["attempt_id"] == start["attempt_id"]]
    if not same_id:
        next_runtime["starts"].append(deepcopy(start))
        return next_runtime, next_seed, _runtime_result(True, "ATTEMPT_STARTED", True)
    if start in same_id:
        return next_runtime, next_seed, _runtime_result(True, "IDEMPOTENT_REPLAY", False)
    return next_runtime, next_seed, _runtime_result(False, "ATTEMPT_IDENTITY_CONFLICT", False)


def end_attempt(
    current: dict[str, list[dict[str, Any]]],
    terminal: dict[str, Any],
    seed_state: dict[str, Any],
) -> tuple[dict[str, list[dict[str, Any]]], dict[str, Any], dict[str, Any]]:
    if not _exact_terminal(terminal):
        raise ValueError("exact terminal record required")
    next_runtime = state(current["starts"], current["terminals"])
    next_seed = deepcopy(seed_state)
    same_id = [
        item for item in next_runtime["terminals"] if item["attempt_id"] == terminal["attempt_id"]
    ]
    if terminal in same_id:
        return next_runtime, next_seed, _runtime_result(True, "IDEMPOTENT_REPLAY", False)
    if same_id:
        return next_runtime, next_seed, _runtime_result(False, "TERMINAL_ATTEMPT_IMMUTABLE", False)
    matching_start = any(
        item["attempt_id"] == terminal["attempt_id"]
        and item["attempt_digest"] == terminal["attempt_digest"]
        for item in next_runtime["starts"]
    )
    if not matching_start:
        return next_runtime, next_seed, _runtime_result(False, "ATTEMPT_NOT_RUNNING", False)
    next_runtime["terminals"].append(deepcopy(terminal))
    code = (
        "ATTEMPT_ENDED_WITH_RESULT"
        if terminal["terminal_kind"] == "RESULT"
        else "ATTEMPT_ENDED_WITH_NO_RESULT"
    )
    return next_runtime, next_seed, _runtime_result(True, code, True)
'''
    target.write_text(text, encoding="utf-8")


def build_release_profiles(seed_profiles_root: Path, output: Path) -> dict[str, object]:
    seed_profiles_root = seed_profiles_root.resolve()
    evidence = check_seed_companion_bases(seed_profiles_root)
    binding = parse_seed_binding()
    records = manifest_records(ROOT)
    if output.exists():
        shutil.rmtree(output)
    (output / "base/seed/en").mkdir(parents=True)
    (output / "base/seed/python").mkdir(parents=True)
    (output / "en").mkdir(parents=True)
    (output / "python").mkdir(parents=True)
    seed_english_rel, seed_english_sha = binding.companions["ENGLISH"]
    seed_python_rel, seed_python_sha = binding.companions["PYTHON"]
    seed_english_target = output / "base/seed/en/Seed.md"
    seed_python_target = output / "base/seed/python/aset_seed_alpha4.py"
    shutil.copy2(seed_profiles_root / seed_english_rel, seed_english_target)
    shutil.copy2(seed_profiles_root / seed_python_rel, seed_python_target)
    require(sha256(seed_english_target) == seed_english_sha, "copied Seed English base drift")
    require(sha256(seed_python_target) == seed_python_sha, "copied Seed Python base drift")
    write_english(output / "en/Runtime.md", seed_english_sha, records)
    write_python(output / "python/aset_runtime_alpha4.py", seed_python_sha, records)
    manifest: dict[str, object] = {
        "document_type": "aset-runtime-alpha4-release-companion-materialization",
        "schema_version": 1,
        "subject_id": "ASET-RUNTIME-ALPHA4",
        "version": "0.1.0-alpha.4",
        "semantic_precedence": "NONE",
        "seed_base": {
            "profile_tree_digest": evidence["profile_tree_digest"],
            "english": {"path": "base/seed/en/Seed.md", "sha256": seed_english_sha},
            "python": {"path": "base/seed/python/aset_seed_alpha4.py", "sha256": seed_python_sha},
        },
        "companions": {
            "controlled_english": "en/Runtime.md",
            "python": "python/aset_runtime_alpha4.py",
        },
        "seed_extension": "PRESERVE-SEED-STATE",
        "records": records,
    }
    (output / "RELEASE_PROFILE_MANIFEST.json").write_text(
        json.dumps(manifest, indent=2, sort_keys=True) + "\n", encoding="utf-8"
    )
    return manifest


def main() -> int:
    import argparse

    parser = argparse.ArgumentParser()
    parser.add_argument("--seed-profiles-root", type=Path, required=True)
    parser.add_argument("--output", type=Path, required=True)
    args = parser.parse_args()
    build_release_profiles(args.seed_profiles_root, args.output)
    print("ALPHA4_RUNTIME_RELEASE_ENGLISH_EXTENSION=PASS")
    print("ALPHA4_RUNTIME_RELEASE_PYTHON_EXTENSION=EXACT_SEED_BASE")
    print("ALPHA4_RUNTIME_RELEASE_PROFILES=PASS")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
